import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/shared/Footer/Footer";
import Navbar from "@/components/shared/Navbar/Navbar";
// import NextTopLoader from "nextjs-toploader";
import { Poppins } from "next/font/google";
import SmoothScrollProvider from "@/components/providers/SmoothScrollProvider";
import ScrollProgressBar from "@/components/providers/ScrollProgressBar";
import ScrollToTopComponent from "@/components/providers/ScrollToTop";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins", 
});

export const metadata: Metadata = {
  title: "Rifat Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        {/* <NextTopLoader color="#FF7639" height={3} showSpinner={false} /> */}
        <ScrollProgressBar/>
        <SmoothScrollProvider>
          <Navbar />
          {children}
          <ScrollToTopComponent/>
          <Footer />
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
